import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";

import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { ReactNode } from "react";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { Locale, locales } from "@/i18n/routing";
import { NextIntlClientProvider } from "next-intl";
import Header from "@/components/Header";
import { MantineProvider } from "@mantine/core";
import DijkerCarousel from "@/components/DijkerCarousel";
import { TanstackQueryProvider } from "@/components/Providers/TanstackQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!locales.includes(locale as Locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={GeistSans.variable}>
        <TanstackQueryProvider>
          <NextIntlClientProvider messages={messages}>
            <MantineProvider>
              <div className={"grid min-h-screen grid-rows-[auto_auto_1fr]"}>
                <Header />
                <DijkerCarousel />

                {children}
              </div>
            </MantineProvider>
          </NextIntlClientProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
